### PR TITLE
rely on factual registry

### PR DESCRIPTION
**Pull request by bilow-factual**

### CODE REVIEW

**Comment by ndigati** [comment]
Why not pin it to the tag you created here? https://github.com/Factual/docker-cdh5-dev/issues/13#issuecomment-401912303

**Comment by cwienberg** [comment]
I'm with @ndigati on this. I think this is a bigger change that we probably need to discuss and figure out.

Leaving dockerhub means we lose autobuilds, among other things.

**Comment by bilow-factual** [comment]
yep, bad idea. thanks. closing.

**Comment by bilow-factual** [comment]
we should point the docker hub repos to the factual images though.

**Comment by ndigati** [comment]
Ya I'll look into it. I know we fixed a couple of them, but I guess we missed one or two of them.

**Pull request closed without merging**
